/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7afd7a9a-fabb-4d3a-9b24-26502d7a9197",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_FW3mTsGMc",
    "aws_user_pools_web_client_id": "4dsmsbq2cbvm903l1l3l0b5ttt",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://qjbm7zpn3natznb5yyft55ybdi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AWS_IAM",
    "aws_appsync_apiKey": "da2-r6a7zjwc6fej7i7wnwx3h4l2au",
    "aws_user_files_s3_bucket": "productcatalogd4ffc6fd926f4285b3a12edc8e7c883ef086b-main",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
